// Generated by scripts/compose-audio.py. Do not edit by hand.
// Music tracks by mood, and every sound effect by name, relative to the page.
export const AUDIO = {
  "music": {
    "harbor": [
      "audio/play-1.mp3?v=69eef05b",
      "audio/play-2.mp3?v=87737548"
    ]
  },
  "effects": {
    "tap": "audio/sfx/tap.mp3?v=5336b0b6",
    "back": "audio/sfx/back.mp3?v=60e49f23",
    "swoosh": "audio/sfx/swoosh.mp3?v=97812b6c",
    "start": "audio/sfx/start.mp3?v=cc331eee",
    "press": "audio/sfx/press.mp3?v=f290b83b",
    "plank-0": "audio/sfx/plank-0.mp3?v=a60252f7",
    "plank-1": "audio/sfx/plank-1.mp3?v=dbbd6420",
    "plank-2": "audio/sfx/plank-2.mp3?v=573e9f96",
    "plank-3": "audio/sfx/plank-3.mp3?v=bc8cf6a4",
    "plank-4": "audio/sfx/plank-4.mp3?v=732535cf",
    "plank-5": "audio/sfx/plank-5.mp3?v=652854c1",
    "plank-6": "audio/sfx/plank-6.mp3?v=9f95ee71",
    "plank-7": "audio/sfx/plank-7.mp3?v=fde2dbf4",
    "snap": "audio/sfx/snap.mp3?v=86d1a85e",
    "open-1": "audio/sfx/open-1.mp3?v=5132f205",
    "open-2": "audio/sfx/open-2.mp3?v=139c1bda",
    "grow-1": "audio/sfx/grow-1.mp3?v=bf34c32d",
    "grow-2": "audio/sfx/grow-2.mp3?v=488f43b4",
    "grow-3": "audio/sfx/grow-3.mp3?v=f3b7615f",
    "grow-4": "audio/sfx/grow-4.mp3?v=93084462",
    "grow-5": "audio/sfx/grow-5.mp3?v=8430a193",
    "grow-6": "audio/sfx/grow-6.mp3?v=3cc0f512",
    "grow-7": "audio/sfx/grow-7.mp3?v=d6c7599c",
    "grow-8": "audio/sfx/grow-8.mp3?v=675edfc9",
    "happy-0": "audio/sfx/happy-0.mp3?v=ed75645c",
    "happy-1": "audio/sfx/happy-1.mp3?v=6edcd510",
    "happy-2": "audio/sfx/happy-2.mp3?v=b94f6441",
    "happy-3": "audio/sfx/happy-3.mp3?v=224667ea",
    "happy-4": "audio/sfx/happy-4.mp3?v=b217bea3",
    "happy-5": "audio/sfx/happy-5.mp3?v=fcf0ca44",
    "happy-6": "audio/sfx/happy-6.mp3?v=0665a45e",
    "splash": "audio/sfx/splash.mp3?v=500d3cbb",
    "snip": "audio/sfx/snip.mp3?v=ae734925",
    "bonk": "audio/sfx/bonk.mp3?v=8b8612c8",
    "undo": "audio/sfx/undo.mp3?v=168b3011",
    "restart": "audio/sfx/restart.mp3?v=b4769b33",
    "drip-0": "audio/sfx/drip-0.mp3?v=3917aa27",
    "drip-1": "audio/sfx/drip-1.mp3?v=62e9c37b",
    "drip-2": "audio/sfx/drip-2.mp3?v=f2241459",
    "drip-3": "audio/sfx/drip-3.mp3?v=73a73357",
    "win": "audio/sfx/win.mp3?v=6e853cd9"
  }
}
