// Generated by scripts/compose-audio.py. Do not edit by hand.
// Music tracks by mood, and every sound effect by name, relative to the page.
export const AUDIO = {
  "music": {
    "home": [
      "audio/home.mp3"
    ],
    "play": [
      "audio/play-1.mp3",
      "audio/play-2.mp3"
    ]
  },
  "effects": {
    "tap": "audio/sfx/tap.mp3",
    "back": "audio/sfx/back.mp3",
    "swoosh": "audio/sfx/swoosh.mp3",
    "start": "audio/sfx/start.mp3",
    "press": "audio/sfx/press.mp3",
    "plank-0": "audio/sfx/plank-0.mp3",
    "plank-1": "audio/sfx/plank-1.mp3",
    "plank-2": "audio/sfx/plank-2.mp3",
    "plank-3": "audio/sfx/plank-3.mp3",
    "plank-4": "audio/sfx/plank-4.mp3",
    "plank-5": "audio/sfx/plank-5.mp3",
    "plank-6": "audio/sfx/plank-6.mp3",
    "plank-7": "audio/sfx/plank-7.mp3",
    "snap": "audio/sfx/snap.mp3",
    "open-1": "audio/sfx/open-1.mp3",
    "open-2": "audio/sfx/open-2.mp3",
    "grow-1": "audio/sfx/grow-1.mp3",
    "grow-2": "audio/sfx/grow-2.mp3",
    "grow-3": "audio/sfx/grow-3.mp3",
    "grow-4": "audio/sfx/grow-4.mp3",
    "grow-5": "audio/sfx/grow-5.mp3",
    "grow-6": "audio/sfx/grow-6.mp3",
    "grow-7": "audio/sfx/grow-7.mp3",
    "grow-8": "audio/sfx/grow-8.mp3",
    "happy-0": "audio/sfx/happy-0.mp3",
    "happy-1": "audio/sfx/happy-1.mp3",
    "happy-2": "audio/sfx/happy-2.mp3",
    "happy-3": "audio/sfx/happy-3.mp3",
    "happy-4": "audio/sfx/happy-4.mp3",
    "happy-5": "audio/sfx/happy-5.mp3",
    "happy-6": "audio/sfx/happy-6.mp3",
    "splash": "audio/sfx/splash.mp3",
    "snip": "audio/sfx/snip.mp3",
    "bonk": "audio/sfx/bonk.mp3",
    "undo": "audio/sfx/undo.mp3",
    "restart": "audio/sfx/restart.mp3",
    "drip-0": "audio/sfx/drip-0.mp3",
    "drip-1": "audio/sfx/drip-1.mp3",
    "drip-2": "audio/sfx/drip-2.mp3",
    "drip-3": "audio/sfx/drip-3.mp3",
    "win": "audio/sfx/win.mp3"
  }
}
