// Generated by scripts/compose-audio.py. Do not edit by hand.
// Music tracks by mood, and every sound effect by name, relative to the page.
export const AUDIO = {
  "music": {
    "title": [
      "audio/title.mp3"
    ],
    "map": [
      "audio/map.mp3"
    ],
    "garden": [
      "audio/garden-1.mp3",
      "audio/garden-2.mp3"
    ],
    "evening": [
      "audio/evening.mp3"
    ]
  },
  "effects": {
    "tap": "audio/sfx/tap.mp3",
    "back": "audio/sfx/back.mp3",
    "swoosh": "audio/sfx/swoosh.mp3",
    "start": "audio/sfx/start.mp3",
    "select-0": "audio/sfx/select-0.mp3",
    "select-1": "audio/sfx/select-1.mp3",
    "select-2": "audio/sfx/select-2.mp3",
    "select-3": "audio/sfx/select-3.mp3",
    "select-4": "audio/sfx/select-4.mp3",
    "select-5": "audio/sfx/select-5.mp3",
    "select-6": "audio/sfx/select-6.mp3",
    "locked": "audio/sfx/locked.mp3",
    "open": "audio/sfx/open.mp3",
    "hop": "audio/sfx/hop.mp3",
    "unlock": "audio/sfx/unlock.mp3",
    "water": "audio/sfx/water.mp3",
    "land": "audio/sfx/land.mp3",
    "erase": "audio/sfx/erase.mp3",
    "place-water-0": "audio/sfx/place-water-0.mp3",
    "place-land-0": "audio/sfx/place-land-0.mp3",
    "place-water-1": "audio/sfx/place-water-1.mp3",
    "place-land-1": "audio/sfx/place-land-1.mp3",
    "place-water-2": "audio/sfx/place-water-2.mp3",
    "place-land-2": "audio/sfx/place-land-2.mp3",
    "place-water-3": "audio/sfx/place-water-3.mp3",
    "place-land-3": "audio/sfx/place-land-3.mp3",
    "place-water-4": "audio/sfx/place-water-4.mp3",
    "place-land-4": "audio/sfx/place-land-4.mp3",
    "place-water-5": "audio/sfx/place-water-5.mp3",
    "place-land-5": "audio/sfx/place-land-5.mp3",
    "place-water-6": "audio/sfx/place-water-6.mp3",
    "place-land-6": "audio/sfx/place-land-6.mp3",
    "place-erase": "audio/sfx/place-erase.mp3",
    "undo": "audio/sfx/undo.mp3",
    "hint": "audio/sfx/hint.mp3",
    "oops": "audio/sfx/oops.mp3",
    "restart": "audio/sfx/restart.mp3",
    "flourish": "audio/sfx/flourish.mp3",
    "village": "audio/sfx/village.mp3",
    "lighthouse": "audio/sfx/lighthouse.mp3",
    "ferry": "audio/sfx/ferry.mp3",
    "pilgrim": "audio/sfx/pilgrim.mp3",
    "win": "audio/sfx/win.mp3"
  }
}
