// Generated by scripts/compose-audio.py. Do not edit by hand.
// Music tracks by mood, and every sound effect by name, relative to the page.
export const AUDIO = {
  "music": {
    "garden": [
      "audio/garden-1.mp3",
      "audio/garden-2.mp3"
    ],
    "bloom": [
      "audio/bloom.mp3"
    ]
  },
  "effects": {
    "pick-1": "audio/sfx/pick-1.mp3",
    "plant-1": "audio/sfx/plant-1.mp3",
    "awake-1": "audio/sfx/awake-1.mp3",
    "bed-1": "audio/sfx/bed-1.mp3",
    "pick-2": "audio/sfx/pick-2.mp3",
    "plant-2": "audio/sfx/plant-2.mp3",
    "awake-2": "audio/sfx/awake-2.mp3",
    "bed-2": "audio/sfx/bed-2.mp3",
    "pick-3": "audio/sfx/pick-3.mp3",
    "plant-3": "audio/sfx/plant-3.mp3",
    "awake-3": "audio/sfx/awake-3.mp3",
    "bed-3": "audio/sfx/bed-3.mp3",
    "pick-4": "audio/sfx/pick-4.mp3",
    "plant-4": "audio/sfx/plant-4.mp3",
    "awake-4": "audio/sfx/awake-4.mp3",
    "bed-4": "audio/sfx/bed-4.mp3",
    "pick-5": "audio/sfx/pick-5.mp3",
    "plant-5": "audio/sfx/plant-5.mp3",
    "awake-5": "audio/sfx/awake-5.mp3",
    "bed-5": "audio/sfx/bed-5.mp3",
    "pick-6": "audio/sfx/pick-6.mp3",
    "plant-6": "audio/sfx/plant-6.mp3",
    "awake-6": "audio/sfx/awake-6.mp3",
    "bed-6": "audio/sfx/bed-6.mp3",
    "sprout": "audio/sfx/sprout.mp3",
    "bud-0": "audio/sfx/bud-0.mp3",
    "bud-1": "audio/sfx/bud-1.mp3",
    "bud-2": "audio/sfx/bud-2.mp3",
    "bud-3": "audio/sfx/bud-3.mp3",
    "bud-4": "audio/sfx/bud-4.mp3",
    "bud-5": "audio/sfx/bud-5.mp3",
    "bloom-0": "audio/sfx/bloom-0.mp3",
    "bloom-1": "audio/sfx/bloom-1.mp3",
    "bloom-2": "audio/sfx/bloom-2.mp3",
    "bloom-3": "audio/sfx/bloom-3.mp3",
    "bloom-4": "audio/sfx/bloom-4.mp3",
    "bloom-5": "audio/sfx/bloom-5.mp3",
    "bloom-6": "audio/sfx/bloom-6.mp3",
    "tick-0": "audio/sfx/tick-0.mp3",
    "tick-1": "audio/sfx/tick-1.mp3",
    "tick-2": "audio/sfx/tick-2.mp3",
    "tick-3": "audio/sfx/tick-3.mp3",
    "dig": "audio/sfx/dig.mp3",
    "droop": "audio/sfx/droop.mp3",
    "bonk": "audio/sfx/bonk.mp3",
    "boing": "audio/sfx/boing.mp3",
    "undo": "audio/sfx/undo.mp3",
    "open": "audio/sfx/open.mp3",
    "close": "audio/sfx/close.mp3",
    "tap": "audio/sfx/tap.mp3",
    "gust": "audio/sfx/gust.mp3",
    "win": "audio/sfx/win.mp3"
  }
}
