// Generated by scripts/compose-audio.py. Do not edit by hand.
// Music tracks by mood, and every sound effect by name, relative to the page.
export const AUDIO = {
  "music": {
    "habitat": [
      "audio/play-1.mp3?v=fcc43b99",
      "audio/play-2.mp3?v=5c7e5eb0"
    ]
  },
  "effects": {
    "tap": "audio/sfx/tap.mp3?v=5336b0b6",
    "back": "audio/sfx/back.mp3?v=60e49f23",
    "swoosh": "audio/sfx/swoosh.mp3?v=97812b6c",
    "start": "audio/sfx/start.mp3?v=c93ac046",
    "squeak-0": "audio/sfx/squeak-0.mp3?v=2a80ba84",
    "squeak-1": "audio/sfx/squeak-1.mp3?v=faab03d4",
    "squeak-2": "audio/sfx/squeak-2.mp3?v=3ed5763b",
    "squeak-3": "audio/sfx/squeak-3.mp3?v=b54141a1",
    "tube-0": "audio/sfx/tube-0.mp3?v=22b8c636",
    "tube-1": "audio/sfx/tube-1.mp3?v=da343466",
    "tube-2": "audio/sfx/tube-2.mp3?v=eecd8b6e",
    "tube-3": "audio/sfx/tube-3.mp3?v=05b0203c",
    "tube-4": "audio/sfx/tube-4.mp3?v=69fbc5c0",
    "tube-5": "audio/sfx/tube-5.mp3?v=982d2ceb",
    "tube-6": "audio/sfx/tube-6.mp3?v=bbbffc28",
    "tube-7": "audio/sfx/tube-7.mp3?v=db0732f3",
    "seed": "audio/sfx/seed.mp3?v=e1a48d14",
    "clear": "audio/sfx/clear.mp3?v=f8ebee81",
    "room-0": "audio/sfx/room-0.mp3?v=5e7b944d",
    "room-1": "audio/sfx/room-1.mp3?v=e5900588",
    "room-2": "audio/sfx/room-2.mp3?v=542496e6",
    "room-3": "audio/sfx/room-3.mp3?v=1a8ccc65",
    "room-4": "audio/sfx/room-4.mp3?v=1842b32f",
    "room-5": "audio/sfx/room-5.mp3?v=6756b31a",
    "room-6": "audio/sfx/room-6.mp3?v=ee0bad69",
    "item": "audio/sfx/item.mp3?v=c3f8c992",
    "hint": "audio/sfx/hint.mp3?v=f8fb8975",
    "bonk": "audio/sfx/bonk.mp3?v=8b8612c8",
    "undo": "audio/sfx/undo.mp3?v=61d3badd",
    "restart": "audio/sfx/restart.mp3?v=afb80020",
    "win": "audio/sfx/win.mp3?v=95e4bb81"
  }
}
